name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "0 0 */3 * *"
  workflow_dispatch:

permissions:
  actions: write
  checks: write
  contents: read
  deployments: read
  id-token: read
  issues: read
  discussions: read
  packages: read
  pages: write
  pull-requests: write
  repository-projects: read


jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: hoppix
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}